### ISSUE TITLE
Fabric Version 1.15.1

### ISSUE THREAD

**Issue by TheAlphaWolf449** [loehnertj/effortless-fabric#3]
### Describe the Suggestion

Any way you can update to add support for Fabric Loader Version 0.15.1, please and thank you!

**Comment by loehnertj** [comment]
Current version targets 0.15.0 - if I am not mistaken, this should be forward-compatible? (i.e. newer loader and/or Fabric-API version should always work)

**Comment by TheAlphaWolf449** [comment]
![Screenshot 2023-12-15 040347](https://github.com/loehnertj/effortless-fabric/assets/81902679/adae462b-d5ca-4843-9164-0fce0d048508)

**Comment by loehnertj** [comment]
Ah I see, this is a problem with the backports. Fixed & made new release 1.7.3.
