### ISSUE TITLE
CRASH

### ISSUE THREAD

**Issue by vinnyg0621** [loehnertj/effortless-fabric#4]
### Describe the Bug

when I saved my world and exited to title, it just crashed.
MC version: 1.20.2

### Reproduction Steps

1. pause the game
2. press "Save and quit to title"
3. open the latest.log
...

### Crash Report or Log

https://gist.github.com/vinnyg0621/457be286b9d00262b7ff609132113d9f

### Other Mods

WorldEdit

### Minecraft Version

1.19.4

### Mod Version

1.6.4

### Fabric Version

0.14.25

### Operating System

Windows 11

**Comment by loehnertj** [comment]
I'm not sure what happened here; unfortunately the log doesn't really tell anything.

Can you have a look in your minecraft profile / "crash-reports" subdirectory, if there is a crash report from that date and time (2023-12-13 18:something)? If yes please post.

Only thing I see is that you have WorldEdit active in parallel, but I think it's unlikely that this is the cause. But you can try deactivating it to see if it still crashes.

**Comment by vinnyg0621** [comment]
I think my anti-virus blocked my java file, but i fixed it
