### ISSUE TITLE
Bug: sound during structure placement.

### ISSUE THREAD

**Issue by Telezhka-the-First** [loehnertj/effortless-fabric#6]
### Describe the Bug

I copied a village well with a bell with "structure" mod, and every time it's preview location changed, the bell rung. It would be logical to make preview structures silent, since they don't actually exist in the world and therefore can't produce sounds.

### Reproduction Steps

1. Copy structure with bell.
2. Move preview structure, don't paste.
3. Hear repeating sound.

### Screenshots and Videos

Real Minecraft version: 1.20.4
Real mod version: 1.8.0

### Minecraft Version

1.19.4

### Mod Version

1.6.4

### Fabric Version

0.15.3

### Operating System

Windows 10

**Comment by loehnertj** [comment]
This was actually a deliberate feature, but I can see how it would be annoying. Will be removed in next release - sound will only be played on click, not on movement anymore.

**Comment by loehnertj** [comment]
Fixed in [v1.8.1](https://github.com/loehnertj/effortless-fabric/releases/tag/version%2F1.8.1).
